name: mobile_app_starter
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  easy_localization: ^3.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_localizations:
    sdk: flutter
  get_it: ^9.2.0
  go_router: ^17.0.1
  json_annotation: ^4.9.0
  logger: ^2.5.0

dev_dependencies:
  build_runner: ^2.7.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^4.1.3
  json_serializable: ^6.11.3

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - .env
    - .env.dev
    - .env.staging
    - .env.prod
