name: mobile_app_starter
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  dio: ^5.2.0+1
  easy_localization: ^3.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.6+5
  flutter_secure_storage: ^8.0.0
  go_router: ^7.1.1
  json_annotation: ^4.8.1
  mobx: ^2.2.0
  provider: ^6.0.5

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.0.2
  json_serializable: ^6.7.0
  mobx_codegen: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
